from fastapi import APIRouter, HTTPException
from fastapi.responses import StreamingResponse
from websql.api import api_get
from reportlab.pdfgen import canvas
from reportlab.lib.pagesizes import A5
import io
import qrcode
from PIL import Image

router = APIRouter(tags=["Tracking PDF Backend"])  # No prefix


@router.get("/download-pdf/{tracking_number}")
def generate_package_pdf(tracking_number: str):
    """
    Generate a compact invoice-style PDF for a package, including QR code.
    """
    try:
        # Fetch package details
        package = api_get(f"/tracking/track/{tracking_number}")
        if not package:
            raise HTTPException(status_code=404, detail="Package not found")

        buffer = io.BytesIO()
        pdf = canvas.Canvas(buffer, pagesize=A5)
        width, height = A5

        # Defensive field access
        extra = package.get('extra_data', {})
        external_id = package.get('external_id', tracking_number)
        sender = extra.get('sender', '')
        recipient = extra.get('recipient', '')
        destination = extra.get('destination', '')
        weight = extra.get('weight_kg', '')

        # ---------- Header ----------
        pdf.setFont("Helvetica-Bold", 20)
        pdf.drawCentredString(width / 2, height - 40, "TRACELET")
        pdf.setFont("Helvetica", 12)
        pdf.drawCentredString(width / 2, height - 60, f"Package Invoice / Tracking")

        # ---------- Package Info ----------
        y = height - 100
        line_height = 20

        pdf.setFont("Helvetica", 12)
        pdf.drawString(30, y, f"Tracking Number: {external_id}")
        y -= line_height
        pdf.drawString(30, y, f"Sender: {sender}")
        y -= line_height
        pdf.drawString(30, y, f"Recipient: {recipient}")
        y -= line_height
        pdf.drawString(30, y, f"Destination: {destination}")
        y -= line_height
        pdf.drawString(30, y, f"Weight (kg): {weight}")

        # ---------- QR Code ----------
        qr = qrcode.QRCode(box_size=6, border=2)  # smaller box for A5
        qr.add_data(external_id)
        qr.make(fit=True)
        img = qr.make_image(fill_color="black", back_color="white")

        img_buffer = io.BytesIO()
        img.save(img_buffer, format="PNG")
        img_buffer.seek(0)
        pil_img = Image.open(img_buffer)

        # Draw QR code on the bottom right
        qr_width = 120
        qr_height = 120
        pdf.drawInlineImage(pil_img, width - qr_width - 30, 30, qr_width, qr_height)

        # ---------- Footer (optional) ----------
        pdf.setFont("Helvetica-Oblique", 8)
        pdf.drawString(30, 20, "Generated by Tracelet Web Tracking System")

        pdf.showPage()
        pdf.save()
        buffer.seek(0)

        return StreamingResponse(
            buffer,
            media_type="application/pdf",
            headers={"Content-Disposition": f"attachment; filename={external_id}.pdf"}
        )

    except HTTPException:
        raise
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"PDF generation failed: {str(e)}")
